# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      labels:
        app: todo-service
    spec:
      serviceAccountName: todo-service-sa # Link to the IRSA Service Account
      containers:
        - name: todo-app
          # --------------------------------------------------------------------------
          # IMPORTANT: Update this image field AFTER ECR is created by Terraform
          # and CI/CD pushes the image.
          # --------------------------------------------------------------------------
          image: "ACCOUNT-ID.dkr.ecr.REGION.amazonaws.com/todo-service:latest"
          
          ports:
            - containerPort: 3000
          
          # --------------------------------------------------------------------------
          # SECURITY HARDENING: Required by Section C
          # - runAsNonRoot, readOnlyRootFilesystem, Drop ALL capabilities
          # --------------------------------------------------------------------------
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000 # Use a common non-root user ID
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
                - NET_RAW

          # Liveness and Readiness Probes
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          resources:
            requests: # Required for EKS scheduling
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
