apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    app: todo-service
spec:
  type: ClusterIP
  selector:
    app: todo-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

